cccs-gs-demo/cccs-legacy-app: fix net_cfg and wifi_cfg empty name checks
We were incorrectly checking that these strings were empty by checking if their
pointer was NULL. Starting in Yocto 5.0 Scarthgap, the "-Werror=address"
compilation flag makes these comparisons trigger compilation errors:

| src/data_request.c: In function 'set_config_cb':
| src/data_request.c:1759:38: error: the comparison will always evaluate as 'false' for the address of 'name' will never be NULL [-Werror=address]
|  1759 |                 if (net_cfgs[i].name == NULL)
|       |                                      ^~
| In file included from src/data_request.c:27:
| /media/gvalcaza/data/dey-projects/5.0/ccimx93-dvk/tmp/work/cortexa55-dey-linux/cccs/git/recipe-sysroot/usr/include/libdigiapix/network.h:191:14: note: 'name' declared here
|   191 |         char name[IFNAMSIZ];
|       |              ^~~~

Change the comparisons to a length check to fix this issue.

Signed-off-by: Gabriel Valcazar <gabriel.valcazar@digi.com>