library: _cc_datapoints: fix DP_FILE_NAME_OUTPUT_FORMAT formatting errors
In Yocto 5.0, the -D_TIME_BITS=64 and -D_FILE_OFFSET_BITS=64 compiler flags
were added to avoid the Y2038 problem with 32-bit timestamps:

https://www.gnu.org/software/gnulib/manual/html_node/Avoiding-the-year-2038-problem.html

Compiling this file with these flags causes the following errors in both places
where the DP_FILE_NAME_OUTPUT_FORMAT pattern is used:

| src/_cc_datapoints.c: In function 'dp_get_backlog_file_path':
| src/_cc_datapoints.c:216:38: error: format '%lu' expects argument of type 'long unsigned int', but argument 5 has type '__time64_t' {aka 'long long int'} [-Werror=format=]
|   216 |         path_len = snprintf(NULL, 0, "%s" DP_FILE_NAME_OUTPUT_FORMAT,
|       |                                      ^~~~
|   217 |                 out_dir, now.tv_sec, now.tv_usec / 1000,
|       |                          ~~~~~~~~~~
|       |                             |
|       |                             __time64_t {aka long long int}
| src/_cc_datapoints.c:40:52: note: format string is defined here
|    40 | #define DP_FILE_NAME_OUTPUT_FORMAT              "%lu%03ld_%s"
|       |                                                  ~~^
|       |                                                    |
|       |                                                    long unsigned int
|       |                                                  %llu
| src/_cc_datapoints.c:216:38: error: format '%ld' expects argument of type 'long int', but argument 6 has type '__suseconds64_t' {aka 'long long int'} [-Werror=format=]
|   216 |         path_len = snprintf(NULL, 0, "%s" DP_FILE_NAME_OUTPUT_FORMAT,
|       |                                      ^~~~
|   217 |                 out_dir, now.tv_sec, now.tv_usec / 1000,
|       |                                      ~~~~~~~~~~~~~~~~~~
|       |                                                  |
|       |                                                  __suseconds64_t {aka long long int}
| src/_cc_datapoints.c:40:57: note: format string is defined here
|    40 | #define DP_FILE_NAME_OUTPUT_FORMAT              "%lu%03ld_%s"
|       |                                                     ~~~~^
|       |                                                         |
|       |                                                         long int
|       |                                                     %03lld

Modify the format pattern using the suggestions in the errors to prevent them.
Make sure to cast the variables to their expected type so that the code builds
regardless of the architecture.

Signed-off-by: Gabriel Valcazar <gabriel.valcazar@digi.com>