src: cc_utils: fix formatting error in timestamp generation
In Yocto 5.0, the -D_TIME_BITS=64 and -D_FILE_OFFSET_BITS=64 compiler flags
were added to avoid the Y2038 problem with 32-bit timestamps:

https://www.gnu.org/software/gnulib/manual/html_node/Avoiding-the-year-2038-problem.html

Compiling this file with these flags results in the following error:

| src/cc_utils.c: In function 'get_timestamp_by_type':
| src/cc_utils.c:64:76: error: format '%ld' expects argument of type 'long int', but argument 3 has type '__suseconds64_t' {aka 'long long int'} [-Werror=format=]
|    64 |                                         sprintf(date + strlen(date), ".%03ldZ", now.tv_usec/10000);
|       |                                                                        ~~~~^    ~~~~~~~~~~~~~~~~~
|       |                                                                            |               |
|       |                                                                            long int        __suseconds64_t {aka long long int}
|       |                                                                        %03lld

Change this format to the suggested one to avoid the error.
Make sure to cast the variables to their expected type so that the code builds
regardless of the architecture.

Signed-off-by: Gabriel Valcazar <gabriel.valcazar@digi.com>